all:
  hosts:
    windows_server:
      ansible_host: "54.242.141.137"
      ansible_user: Administrator
      ansible_password: "PLACEHOLDER_PASSWORD"
      ansible_connection: winrm
      ansible_winrm_transport: basic
      ansible_winrm_server_cert_validation: ignore
      ansible_port: 5985