name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Build Application
      run: |
        cd webapp/WebApp
        dotnet restore
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ../publish
    
    - name: Create Deployment Package
      run: |
        cd webapp
        zip -r webapp-${{ github.sha }}.zip publish/
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Ansible
      run: |
        pip install ansible pywinrm
    
    - name: Deploy with Ansible
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        WINDOWS_PASSWORD: ${{ secrets.WINDOWS_PASSWORD }}
      run: |
        cd ansible
        ansible-playbook -i inventory.yml deploy-app.yml \
          --extra-vars "ec2_public_ip=$EC2_PUBLIC_IP windows_password=$WINDOWS_PASSWORD app_source_path=../webapp/publish/"